/**
 ******************************************************************************
 * @file      main.c
 * @brief     Simple demonstration project for displaying static text on a
 * 16x2 I2C LCD using the S32K144 microcontroller.
 * @author    [Vo Minh Luong]
 * @date      Oct 17, 2025
 ******************************************************************************
 */

/*============================================================================*/
/* Includes                                   */
/*============================================================================*/
#include "S32K144.h"
#include "sdk_project_config.h"
#include "clock_config.h"
#include "pin_mux.h"
#include "peripherals_lpi2c_config_1.h"
#include "lpi2c_driver.h"   // LPI2C low-level driver
#include "osif.h"           // OS Interface for OSIF_TimeDelay()

/*============================================================================*/
/* Defines                                   */
/*============================================================================*/

// HD44780 LCD Controller Commands
#define LCD_CLEAR_DISPLAY   0x01
#define LCD_RETURN_HOME     0x02
#define LCD_ENTRY_MODE_SET  0x04
#define LCD_DISPLAY_CONTROL 0x08
#define LCD_FUNCTION_SET    0x20
#define LCD_SET_DDRAM_ADDR  0x80

/*============================================================================*/
/* Global Variables                                */
/*============================================================================*/

// State structure for the LPI2C0 master driver instance.
// This is required by the LPI2C driver to manage its internal state.
lpi2c_master_state_t g_lpi2c0MasterState;

/*============================================================================*/
/* Private Function Prototypes                         */
/*============================================================================*/

void WDOG_disable(void);
void LCD_SendByte(uint8_t data, uint8_t rs_bit);
void LCD_SendCommand(uint8_t command);
void LCD_SendData(uint8_t data);
void LCD_SendString(char *str);
void LCD_Init(void);

/*============================================================================*/
/* Main Function                                  */
/*============================================================================*/

int main(void)
{
    /*--------------------------------------------------*/
    /* 1. One-Time System Initialization       */
    /*--------------------------------------------------*/
    WDOG_disable();

    // Initialize system clocks and pins based on the S32 Configuration Tools setup.
    // This function is typically generated by the tool and found in board.c.
    CLOCK_DRV_Init(&clockMan1_InitConfig0);
    PINS_DRV_Init(NUM_OF_CONFIGURED_PINS0, g_pin_mux_InitConfigArr0);

    // Initialize the LPI2C0 peripheral in master mode using the generated configuration.
    LPI2C_DRV_MasterInit(INST_LPI2C0, &lpi2c0_MasterConfig0, &g_lpi2c0MasterState);

    // Initialize the LCD display.
    LCD_Init();

    /*--------------------------------------------------*/
    /* 2. Display Content on LCD               */
    /*--------------------------------------------------*/
    // --- Display on the First Line ---
    // Move cursor to the beginning of the first line (address 0x80).
    LCD_SendCommand(0x80);
    OSIF_TimeDelay(100); // Small delay to ensure the LCD has processed the command.

    // Send the string to be displayed on the first line.
    LCD_SendString("S32K144 Demo");

    // --- Display on the Second Line (Added) ---
    // Move cursor to the beginning of the second line (address 0xC0).
    LCD_SendCommand(0xC0);
    OSIF_TimeDelay(100); // Small delay for safety.

    // Send the string to be displayed on the second line.
    LCD_SendString("LCD 1602 OK!");

    /*--------------------------------------------------*/
    /* 3. Enter Infinite Loop                 */
    /*--------------------------------------------------*/
    // The microcontroller will do nothing further, just keep the LCD display active.
    while (1)
    {
        // Program execution remains here.
    }
    
}

/*============================================================================*/
/* Private Function Implementations                       */
/*============================================================================*/

/**
 * @brief Disables the Watchdog timer to prevent unintended system resets
 * during development and simple applications.
 */
void WDOG_disable(void)
{
    WDOG->CNT = 0xD928C520;   // Unlock sequence
    WDOG->TOVAL = 0x0000FFFF; // Set max timeout value
    WDOG->CS = 0x00002100;    // Disable watchdog
}

/**
 * @brief Sends a single byte to the LCD via the I2C interface.
 * @details This function splits the byte into two 4-bit nibbles and sends them sequentially,
 * toggling the Enable (EN) pin for each nibble to latch the data. It uses the
 * LPI2C blocking send function.
 * @param data The 8-bit data byte to send.
 * @param rs_bit Register Select bit (0 for command, 1 for data/character).
 */
void LCD_SendByte(uint8_t data, uint8_t rs_bit)
{
    status_t status;
    uint8_t high_nibble = data & 0xF0;
    uint8_t low_nibble = (data << 4) & 0xF0;
    uint8_t i2c_payload[4];

    // The I2C backpack requires a specific sequence to simulate a 4-bit parallel interface.
    // Each nibble needs an Enable (EN) pulse (high then low).
    // The payload is constructed as: [Data | RS | Backlight | EN]

    // Payload for the high nibble (EN pulse)
    i2c_payload[0] = (high_nibble | rs_bit | 0x08 | 0x04); // EN = 1
    i2c_payload[1] = (high_nibble | rs_bit | 0x08);        // EN = 0

    // Payload for the low nibble (EN pulse)
    i2c_payload[2] = (low_nibble | rs_bit | 0x08 | 0x04);  // EN = 1
    i2c_payload[3] = (low_nibble | rs_bit | 0x08);         // EN = 0

    // Send the entire 4-byte sequence in a single blocking I2C transaction.
    status = LPI2C_DRV_MasterSendDataBlocking(INST_LPI2C0, i2c_payload, 4, true, 100);
    (void)status; // Suppress unused variable warning if not in debug mode.
}

/**
 * @brief Sends a command byte to the LCD.
 * @param command The command byte to send (e.g., LCD_CLEAR_DISPLAY).
 */
void LCD_SendCommand(uint8_t command)
{
    LCD_SendByte(command, 0); // RS bit is 0 for commands.
}

/**
 * @brief Sends a data character to the LCD to be displayed.
 * @param data The character byte to send (e.g., 'A').
 */
void LCD_SendData(uint8_t data)
{
    LCD_SendByte(data, 1); // RS bit is 1 for data.
}

/**
 * @brief Sends a null-terminated string to the LCD.
 * @param str Pointer to the string to be displayed.
 */
void LCD_SendString(char *str)
{
    while (*str)
    {
        LCD_SendData(*str++);
    }
}

/**
 * @brief Initializes the LCD into 4-bit communication mode.
 * @details Sends the required sequence of commands as per the HD44780 datasheet
 * to configure the LCD for 4-bit operation after power-on.
 */
void LCD_Init(void)
{
    // Wait for the LCD to stabilize after power-on.
    OSIF_TimeDelay(50);

    // --- Special initialization sequence required for 4-bit mode ---
    LCD_SendByte(0x30, 0);
    OSIF_TimeDelay(5);
    LCD_SendByte(0x30, 0);
    OSIF_TimeDelay(1);
    LCD_SendByte(0x30, 0);
    OSIF_TimeDelay(1);
    LCD_SendByte(0x20, 0); // Finally, set to 4-bit interface.
    OSIF_TimeDelay(1);

    // --- Standard configuration commands after setting 4-bit mode ---
    LCD_SendCommand(LCD_FUNCTION_SET | 0x08);    // Function Set: 4-bit mode, 2 lines, 5x8 font
    LCD_SendCommand(LCD_DISPLAY_CONTROL | 0x04); // Display Control: Display on, cursor off, blink off
    LCD_SendCommand(LCD_CLEAR_DISPLAY);          // Clear entire display
    OSIF_TimeDelay(2);                           // This command takes longer to execute
    LCD_SendCommand(LCD_ENTRY_MODE_SET | 0x02);  // Entry Mode Set: Increment cursor, no display shift
    LCD_SendCommand(LCD_RETURN_HOME);            // Return cursor to home position (0,0)
}

